'use strict';

/* Relay Moth Forest v4.14 — on-canvas WYSIWYG room editor.
 * Editor ownership is deliberately presentation/authoring-only. Runtime gameplay
 * systems continue to consume relay_moth_maps.json through Room as before.
 */
(function(root){
  const TILE=16, GRID_W=40, GRID_H=19, PLAY_H=304, W=640, H=360;
  const clone=v=>JSON.parse(JSON.stringify(v));
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const key=(x,y)=>`${x},${y}`;
  const inside=(x,y)=>x>=0&&x<GRID_W&&y>=0&&y<GRID_H;
  const intersects=(a,b)=>!(a.x1<b.x0||a.x0>b.x1||a.y1<b.y0||a.y0>b.y1);
  const rectFrom=(a,b)=>({x0:Math.min(a.x,b.x),y0:Math.min(a.y,b.y),x1:Math.max(a.x,b.x),y1:Math.max(a.y,b.y)});

  class WysiwygEditor{
    constructor(game){
      this.game=game;this.active=false;this.tool='brush';this.category='tiles';this.choice={kind:'path',label:'Path'};
      this.overlay=document.querySelector('#editorOverlay');this.ctx=this.overlay.getContext('2d');
      this.panel=document.querySelector('#wysiwygEditor');this.toolbar=document.querySelector('#editorToolbar');this.palettePanel=document.querySelector('#editorPalette');this.palette=document.querySelector('#editorPaletteGrid');this.search=document.querySelector('#editorPaletteSearch');
      this.status=document.querySelector('#editorStatus');this.hover={x:320,y:152};this.pointerDown=false;this.pointerButton=0;this.dragMode=null;this.dragStart=null;this.dragNow=null;this.selection=[];this.clipboard=null;this.undo=[];this.redo=[];this.transaction=null;this.paintVisited=new Set();this.showGrid=true;this.nextDecorId=1;this._renderQueued=false;
      this.bind();this.buildCategories();this.buildPalette();this.renderOverlay();
    }
    roomKey(){return this.game.room?.key||this.game.storyData.rooms[this.game.state.room]?.key}
    rawRoom(){return this.game.maps.rooms[this.roomKey()]}
    toggle(force=null){const next=force==null?!this.active:!!force;if(next===this.active)return;this.active=next;document.body.classList.toggle('wysiwygEdit',next);if(!next)document.body.classList.remove('wysiwygChromeHidden');this.panel.classList.toggle('hidden',!next);this.overlay.classList.toggle('editorActive',next);if(next){this.selection=[];this.resetPointerState();this.recountIds();this.buildPalette();this.game.toast('WYSIWYG EDITOR · left paint/select · right remove',1.8)}else{this.selection=[];if(this.transaction)this.commitTransaction();this.resetPointerState();this.renderOverlay();this.game.toast('Editor closed · gameplay view restored',1.3)}this.updateStatus()}
    bind(){
      this.panel?.querySelectorAll('button').forEach(b=>b.type='button');
      this.overlay.addEventListener('contextmenu',e=>e.preventDefault());
      this.overlay.addEventListener('pointerdown',e=>this.onDown(e));
      this.overlay.addEventListener('pointermove',e=>this.onMove(e));
      this.overlay.addEventListener('pointerup',e=>this.onUp(e));
      this.overlay.addEventListener('pointercancel',e=>this.onUp(e));
      this.search?.addEventListener('input',()=>this.buildPalette());
      document.querySelectorAll('[data-editor-tool]').forEach(b=>b.addEventListener('click',()=>this.setTool(b.dataset.editorTool)));
      document.querySelectorAll('[data-editor-category]').forEach(b=>b.addEventListener('click',()=>{this.category=b.dataset.editorCategory;const entries=this.entries();if(entries.length)this.choice=entries[0];document.querySelectorAll('[data-editor-category]').forEach(x=>x.classList.toggle('active',x===b));this.buildPalette();this.updateStatus();this.renderOverlay()}));
      document.querySelector('#editorUndo')?.addEventListener('click',()=>this.undoOne());
      document.querySelector('#editorRedo')?.addEventListener('click',()=>this.redoOne());
      document.querySelector('#editorCopy')?.addEventListener('click',()=>this.copySelection());
      document.querySelector('#editorPaste')?.addEventListener('click',()=>this.pasteClipboard());
      document.querySelector('#editorDelete')?.addEventListener('click',()=>this.deleteSelection());
      document.querySelector('#editorGrid')?.addEventListener('click',e=>{this.showGrid=!this.showGrid;e.currentTarget.classList.toggle('active',this.showGrid);this.renderOverlay()});
      document.querySelector('#editorChrome')?.addEventListener('click',()=>this.toggleChrome());
      document.querySelector('#editorSave')?.addEventListener('click',()=>this.saveProject());
      document.querySelector('#editorDownload')?.addEventListener('click',()=>this.downloadMaps());
      document.querySelector('#editorClose')?.addEventListener('click',()=>this.toggle(false));
      window.addEventListener('keydown',e=>this.onKey(e),true);
      window.addEventListener('resize',()=>this.renderOverlay());
      const shield=e=>{if(!this.active)return;e.stopPropagation()};
      for(const ui of [this.toolbar,this.palettePanel])if(ui){ui.addEventListener('pointerdown',shield);ui.addEventListener('pointerup',shield);ui.addEventListener('pointermove',shield);ui.addEventListener('contextmenu',shield)}
    }
    releasePointer(pointerId=null){try{if(pointerId!=null&&this.overlay.hasPointerCapture?.(pointerId))this.overlay.releasePointerCapture(pointerId)}catch(_){} }
    resetPointerState(pointerId=null){this.releasePointer(pointerId);this.pointerDown=false;this.pointerButton=0;this.dragMode=null;this.dragStart=null;this.dragNow=null;this.moveOriginal=null;this.paintVisited.clear()}
    toggleChrome(){document.body.classList.toggle('wysiwygChromeHidden');const b=document.querySelector('#editorChrome');if(b)b.textContent=document.body.classList.contains('wysiwygChromeHidden')?'SHOW UI':'HIDE UI';this.renderOverlay()}
    onKey(e){if(!this.active)return;if(e.key==='F2'||e.key==='F11')return;e.stopImmediatePropagation();const target=e.target?.tagName;if(target==='INPUT'||target==='TEXTAREA'||target==='SELECT')return;if(e.key==='Tab'){e.preventDefault();this.toggleChrome();return}
      if(e.key==='Escape'){e.preventDefault();if(this.dragMode){this.cancelTransaction();this.dragMode=null;this.renderOverlay()}else this.toggle(false);return}
      const k=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?this.redoOne():this.undoOne();return}if((e.ctrlKey||e.metaKey)&&k==='y'){e.preventDefault();this.redoOne();return}if((e.ctrlKey||e.metaKey)&&k==='c'){e.preventDefault();this.copySelection();return}if((e.ctrlKey||e.metaKey)&&k==='v'){e.preventDefault();this.pasteClipboard();return}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();this.deleteSelection();return}
      if(k==='b'){this.setTool('brush');e.preventDefault()}else if(k==='s'){this.setTool('select');e.preventDefault()}else if(k==='o'){this.setTool('object');e.preventDefault()}else if(k==='e'){this.setTool('erase');e.preventDefault()}else if(k==='v'){this.setTool('move');e.preventDefault()}
    }
    setTool(tool){this.tool=tool;document.querySelectorAll('[data-editor-tool]').forEach(b=>b.classList.toggle('active',b.dataset.editorTool===tool));this.overlay.style.cursor=(tool==='select'||tool==='object')?'crosshair':tool==='move'?'move':tool==='erase'?'not-allowed':'crosshair';this.updateStatus();this.renderOverlay()}
    logical(ev){const r=this.overlay.getBoundingClientRect();return{x:clamp((ev.clientX-r.left)/r.width*W,0,W-.001),y:clamp((ev.clientY-r.top)/r.height*H,0,H-.001)}}
    tileAt(p){return[clamp(Math.floor(p.x/TILE),0,GRID_W-1),clamp(Math.floor(p.y/TILE),0,GRID_H-1)]}
    beginTransaction(label){if(this.transaction)return;this.transaction={label,before:clone(this.rawRoom())}}
    commitTransaction(){if(!this.transaction)return;const after=JSON.stringify(this.rawRoom()),before=JSON.stringify(this.transaction.before);if(after!==before){this.undo.push(this.transaction);if(this.undo.length>48)this.undo.shift();this.redo.length=0}this.transaction=null;this.updateStatus()}
    cancelTransaction(){if(!this.transaction)return;this.game.maps.rooms[this.roomKey()]=this.transaction.before;this.transaction=null;this.rebuildRoom()}
    undoOne(){if(!this.undo.length)return;const u=this.undo.pop(),current=clone(this.rawRoom());this.redo.push({label:u.label,before:current});this.game.maps.rooms[this.roomKey()]=clone(u.before);this.selection=[];this.rebuildRoom();this.game.toast('Editor undo · '+u.label,1.1);this.updateStatus()}
    redoOne(){if(!this.redo.length)return;const u=this.redo.pop(),current=clone(this.rawRoom());this.undo.push({label:'redo',before:current});this.game.maps.rooms[this.roomKey()]=clone(u.before);this.selection=[];this.rebuildRoom();this.game.toast('Editor redo',1.1);this.updateStatus()}
    recountIds(){let n=1;for(const d of this.rawRoom()?.editor_decor||[]){const m=String(d.editor_id||'').match(/(\d+)$/);if(m)n=Math.max(n,Number(m[1])+1)}this.nextDecorId=n}
    buildCategories(){document.querySelectorAll('[data-editor-category]').forEach(b=>b.classList.toggle('active',b.dataset.editorCategory===this.category))}
    entries(){const art=this.game.art,roles=art.roles||{},arr=[];
      if(this.category==='tiles')return[
        {kind:'path',label:'Path tile',swatch:'#b18b58'},{kind:'water',label:'Water tile',swatch:'#277a9a'},{kind:'solid',label:'Solid blocker',sprite:(roles.blocker_variants||roles.blockers||[])[0]},{kind:'clear',label:'Clear tile',swatch:'#293a38'}];
      if(this.category==='blockers')for(const s of roles.blocker_variants||roles.blockers||[])arr.push({kind:'blocker',label:s,sprite:s});
      if(this.category==='trees')for(const s of roles.tree_blockers||[])arr.push({kind:'tree',label:s,sprite:s});
      if(this.category==='decor')for(const s of [...new Set([...(roles.decor_plants||[]),...(roles.foliage_v401_all||[])])])arr.push({kind:'decor',label:s,sprite:s});
      if(this.category==='grass')return[
        {kind:'grass',label:'Grass · light',radius:17,density:.85,swatch:'#377f61'},
        {kind:'grass',label:'Grass · normal',radius:22,density:1.25,swatch:'#3da875'},
        {kind:'grass',label:'Grass · dense',radius:27,density:1.75,swatch:'#59d892'},
        {kind:'grass',label:'Grass · lush',radius:32,density:2.25,swatch:'#78f4ac'}];
      if(this.category==='lamps')for(const s of (roles.lamps||[]).filter(x=>x.startsWith('lamp_')||x.startsWith('lantern_')))arr.push({kind:'lamp',label:s,sprite:s});
      if(this.category==='robots')for(const v of roles.decor_robots||Object.keys(roles.robot_variants||{})){const sprite=roles.robot_variants?.[v]?.idle;arr.push({kind:'robot',label:v,variant:v,sprite})}
      if(this.category==='moths')for(let i=0;i<(roles.moths||[]).length;i++)arr.push({kind:'moth',label:`Relay moth ${i+1}`,variant:i,sprite:roles.moths[i],colour_index:55+i*34});
      if(this.category==='wildlife')for(const [kind,frames] of Object.entries(roles.creatures||{}))arr.push({kind:'wildlife',label:kind.replaceAll('_',' '),wildlifeKind:kind,sprite:frames.idle,count:1});
      if(this.category==='mini')for(const [variant,frames] of Object.entries(roles.mini_robots||{}))arr.push({kind:'mini',label:`mini ${variant}`,variant,sprite:frames.idle,count:2});
      if(this.category==='ambient')for(const [label,sprite,alpha,scale] of [['Moon + star wave','moon_star_wave',.50,.90],['Moon','guide_moon',.55,.85],['Star swirl','swirl_large',.40,.75]])if(art.regions[sprite])arr.push({kind:'ambient',label,sprite,alpha,scale});
      return arr;
    }
    buildPalette(){if(!this.palette)return;const q=(this.search?.value||'').trim().toLowerCase(),entries=this.entries().filter(e=>!q||e.label.toLowerCase().includes(q));this.palette.innerHTML='';for(const e of entries){const b=document.createElement('button');b.type='button';b.className='editorPaletteItem';b.title=e.label;b.dataset.kind=e.kind;const cv=document.createElement('canvas');cv.width=54;cv.height=48;const x=cv.getContext('2d');x.clearRect(0,0,54,48);if(e.sprite&&this.game.art.regions[e.sprite]){const r=this.game.art.region(e.sprite),scale=Math.min(48/r[2],42/r[3],1),dw=r[2]*scale,dh=r[3]*scale;x.imageSmoothingEnabled=true;x.drawImage(this.game.art.img,r[0],r[1],r[2],r[3],27-dw/2,47-dh,dw,dh)}else{x.fillStyle=e.swatch||'#6b8792';x.fillRect(9,9,36,30);x.strokeStyle='#dff';x.strokeRect(9.5,9.5,35,29)}const span=document.createElement('span');span.textContent=e.label;b.append(cv,span);b.onclick=()=>{this.choice=e;this.setTool('brush');this.palette.querySelectorAll('.editorPaletteItem').forEach(z=>z.classList.toggle('active',z===b));this.updateStatus();this.renderOverlay()};this.palette.append(b)}if(entries.length)this.palette.firstElementChild?.classList.toggle('active',this.choice?.label===entries[0].label&&this.choice?.kind===entries[0].kind)}
    onDown(e){if(!this.active)return;e.preventDefault();e.stopPropagation();const p=this.logical(e);if(p.y>=PLAY_H||![0,2].includes(e.button)){this.releasePointer(e.pointerId);return}this.overlay.setPointerCapture?.(e.pointerId);this.hover=p;this.pointerDown=true;this.pointerButton=e.button;this.dragStart=p;this.dragNow=p;this.paintVisited.clear();
      if(e.button===2){this.beginTransaction('remove decoration');this.dragMode='eraseDecor';this.eraseAt(p,true);return}
      if(this.tool==='erase'){this.beginTransaction('erase');this.dragMode='erase';this.eraseAt(p,false);return}
      if(e.button!==0)return;
      if(this.tool==='brush'){this.beginTransaction('paint');this.dragMode='paint';this.paintAt(p);return}
      const hit=this.hitAt(p,true,this.tool==='object');
      if(this.tool==='move'||((this.tool==='select'||this.tool==='object')&&hit&&this.selection.some(s=>this.sameRef(s,hit)))){if(hit&&!this.selection.some(s=>this.sameRef(s,hit)))this.selection=[hit];if(this.selection.length){this.beginTransaction('move selection');this.dragMode='move';this.moveOriginal=this.captureSelectionState();this.renderOverlay();return}}
      if(this.tool==='object'){if(hit&&!e.shiftKey)this.selection=[hit];else if(hit&&e.shiftKey){const ix=this.selection.findIndex(s=>this.sameRef(s,hit));if(ix>=0)this.selection.splice(ix,1);else this.selection.push(hit)}else if(!e.shiftKey)this.selection=[];this.dragMode='clickSelect';this.renderOverlay();return}
      if(this.tool==='select'){if(hit&&!e.shiftKey){this.selection=[hit];this.dragMode='clickSelect'}else if(hit&&e.shiftKey){const ix=this.selection.findIndex(s=>this.sameRef(s,hit));if(ix>=0)this.selection.splice(ix,1);else this.selection.push(hit);this.dragMode='clickSelect'}else{if(!e.shiftKey)this.selection=[];this.dragMode='selectBox'}this.renderOverlay()}
    }
    onMove(e){if(!this.active)return;e.stopPropagation();let p=this.logical(e);if(this.pointerDown&&p.y>=PLAY_H)p={x:p.x,y:PLAY_H-.001};this.hover=p;this.dragNow=p;if(!this.pointerDown){this.renderOverlay();return}if(this.dragMode==='paint')this.paintAt(p);else if(this.dragMode==='erase')this.eraseAt(p,false);else if(this.dragMode==='eraseDecor')this.eraseAt(p,true);else if(this.dragMode==='move')this.previewMove(p);else this.renderOverlay()}
    onUp(e){if(!this.active){this.releasePointer(e.pointerId);return}e.stopPropagation();const p=this.logical(e);this.hover=p;this.dragNow=p;if(this.dragMode==='selectBox'&&this.dragStart){const r=rectFrom(this.dragStart,p);this.selection=this.collectItems().filter(it=>intersects(it.bbox,r))}else if(this.dragMode==='move'){this.applyMove(p);this.commitTransaction()}else if(this.dragMode==='paint'||this.dragMode==='erase'||this.dragMode==='eraseDecor')this.commitTransaction();this.releasePointer(e.pointerId);this.pointerDown=false;this.dragMode=null;this.dragStart=null;this.dragNow=null;this.moveOriginal=null;this.renderOverlay();this.updateStatus()}
    paintAt(p){const c=this.choice;if(!c)return;const [tx,ty]=this.tileAt(p),visit=(c.kind==='decor'||c.kind==='grass')?`${c.kind}:${Math.round(p.x/4)},${Math.round(p.y/4)}`:`${c.kind}:${tx},${ty}`;if(this.paintVisited.has(visit))return;this.paintVisited.add(visit);if(c.kind==='decor'||c.kind==='grass'){if(this.dragStart&&Math.hypot(p.x-this.dragStart.x,p.y-this.dragStart.y)<3&&this.paintVisited.size>1)return}
      const r=this.rawRoom();r.decor_exclusions=(r.decor_exclusions||[]).filter(q=>(Array.isArray(q)?key(q[0],q[1]):String(q))!==key(tx,ty));if(c.kind==='path'||c.kind==='water'||c.kind==='solid'||c.kind==='clear'||c.kind==='blocker'||c.kind==='tree')this.placeTile(c,tx,ty);else if(c.kind==='decor'||c.kind==='ambient'){r.editor_decor=r.editor_decor||[];r.editor_decor.push({editor_id:`decor_${this.nextDecorId++}`,x:Math.round(p.x),y:Math.min(PLAY_H,Math.round(p.y)),sprite:c.sprite,scale:c.scale??1,alpha:c.alpha??1,flip:false,element:c.kind==='ambient'?'stars':undefined})}else if(c.kind==='grass'){r.grass_clumps=r.grass_clumps||[];r.grass_clumps.push({x:Math.round(p.x*100)/100,y:Math.min(PLAY_H,Math.round(p.y*100)/100),radius:c.radius,density:c.density,seed:(Date.now()+this.paintVisited.size*7919)>>>0})}else if(c.kind==='lamp'){this.replaceByTile(r.decor_lamps=r.decor_lamps||[],tx,ty,{tile:[tx,ty],lamp:c.sprite})}else if(c.kind==='robot'){this.replaceByTile(r.decor_robots=r.decor_robots||[],tx,ty,{tile:[tx,ty],variant:c.variant})}else if(c.kind==='moth'){r.moth_pickups=r.moth_pickups||[];r.moth_pickups.push({id:this.uniqueId('editor_moth',r.moth_pickups),tile:[tx,ty],variant:c.variant||0,colour_index:c.colour_index??210})}else if(c.kind==='wildlife'){r.creature_groups=r.creature_groups||[];r.creature_groups.push({id:this.uniqueId(`editor_${c.wildlifeKind}`,r.creature_groups),kind:c.wildlifeKind,count:c.count||1,spawn:[tx,ty],seed:(Date.now()+this.nextDecorId*3571)>>>0})}else if(c.kind==='mini'){r.mini_robot_groups=r.mini_robot_groups||[];r.mini_robot_groups.push({id:this.uniqueId(`editor_mini_${c.variant}`,r.mini_robot_groups),variant:c.variant,count:c.count||1,spawn:[tx,ty],seed:(Date.now()+this.nextDecorId*4111)>>>0})}this.rebuildRoom()}
    uniqueId(prefix,arr){const used=new Set((arr||[]).map(x=>String(x.id||'')));let i=1,id=`${prefix}_${i}`;while(used.has(id))id=`${prefix}_${++i}`;return id}
    replaceByTile(arr,tx,ty,obj){for(let i=arr.length-1;i>=0;i--)if(arr[i].tile?.[0]===tx&&arr[i].tile?.[1]===ty)arr.splice(i,1);arr.push(obj)}
    placeTile(c,tx,ty){if(!inside(tx,ty))return;const r=this.rawRoom(),k=key(tx,ty);for(const name of ['walls','water','path_cells'])r[name]=(r[name]||[]).filter(q=>key(q[0],q[1])!==k);if(r.blocker_styles)delete r.blocker_styles[k];r.large_trees=(r.large_trees||[]).filter(t=>key(t.tile?.[0],t.tile?.[1])!==k);
      if(c.kind==='clear')return;if(c.kind==='path'){r.path_cells.push([tx,ty]);return}if(c.kind==='water'){r.water.push([tx,ty]);return}r.walls.push([tx,ty]);r.blocker_styles=r.blocker_styles||{};const sprite=c.sprite||(this.game.art.roles.blocker_variants||[])[0];if(c.kind==='tree'){r.blocker_styles[k]={sprite,kind:'tree',lut:'blockers',scale:1,canopy:true};r.large_trees.push({tile:[tx,ty],sprite})}else r.blocker_styles[k]={sprite,kind:'blocker',lut:'blockers',scale:1}}
    eraseAt(p,decorOnly=false){const hit=this.hitAt(p,!decorOnly);if(hit){this.removeRef(hit);this.selection=this.selection.filter(s=>!this.sameRef(s,hit));this.rebuildRoom();return}if(decorOnly){const [tx,ty]=this.tileAt(p),r=this.rawRoom(),k=key(tx,ty);r.decor_exclusions=r.decor_exclusions||[];if(!r.decor_exclusions.some(q=>(Array.isArray(q)?key(q[0],q[1]):String(q))===k)){r.decor_exclusions.push([tx,ty]);this.rebuildRoom()}}}
    sameRef(a,b){return a&&b&&a.type===b.type&&a.id===b.id}
    collectItems(){const r=this.rawRoom(),out=[],wallSet=new Set((r.walls||[]).map(q=>key(q[0],q[1]))),treeMap=new Map((r.large_trees||[]).map((x,i)=>[key(x.tile?.[0],x.tile?.[1]),i]));for(const q of r.walls||[]){const k=key(q[0],q[1]),style=r.blocker_styles?.[k]||{},ti=treeMap.get(k);if(ti!=null){const t=r.large_trees[ti],bbox=this.spriteBBox(t.sprite,q[0]*TILE+TILE/2,q[1]*TILE+TILE+2,true);out.push({type:'tree',id:k,tile:[...q],index:ti,bbox})}else{const sprite=style.sprite||(this.game.art.roles.blocker_variants||[])[0],bbox=this.spriteBBox(sprite,q[0]*TILE+TILE/2,q[1]*TILE+TILE+2,true);out.push({type:'blocker',id:k,tile:[...q],bbox})}}
      for(const q of r.water||[])if(!wallSet.has(key(q[0],q[1])))out.push({type:'water',id:key(q[0],q[1]),tile:[...q],bbox:{x0:q[0]*TILE,y0:q[1]*TILE,x1:(q[0]+1)*TILE,y1:(q[1]+1)*TILE}});
      for(const q of r.path_cells||[])if(!wallSet.has(key(q[0],q[1])))out.push({type:'path',id:key(q[0],q[1]),tile:[...q],bbox:{x0:q[0]*TILE,y0:q[1]*TILE,x1:(q[0]+1)*TILE,y1:(q[1]+1)*TILE}});
      (r.editor_decor||[]).forEach((d,i)=>out.push({type:'decor',id:d.editor_id||`decor:${i}`,index:i,obj:d,bbox:this.spriteBBox(d.sprite,d.x,d.y,true,this.game.painter.spriteScale(d.sprite,d.scale??1),Number(d.rot)||0)}));
      (r.grass_clumps||[]).forEach((g,i)=>out.push({type:'grass',id:`grass:${i}`,index:i,obj:g,bbox:{x0:g.x-g.radius,y0:g.y-g.radius*.7,x1:g.x+g.radius,y1:g.y+g.radius*.7}}));
      (r.decor_lamps||[]).forEach((d,i)=>{const [tx,ty]=d.tile||[0,0],x=tx*TILE+TILE/2,y=ty*TILE+TILE/2;out.push({type:'lamp',id:`lamp:${i}`,index:i,obj:d,tile:[tx,ty],bbox:{x0:x-10,y0:y-48,x1:x+10,y1:y+13}})});
      (r.decor_robots||[]).forEach((d,i)=>{const [tx,ty]=d.tile||[0,0],x=tx*TILE+TILE/2,y=ty*TILE+TILE/2+10,s=this.game.art.roles.robot_variants?.[d.variant||'cream']?.idle;out.push({type:'robot',id:`robot:${i}`,index:i,obj:d,tile:[tx,ty],bbox:this.spriteBBox(s,x,y,true,.84)})});
      for(const obj of this.game.room.spec.objects||[]){const tile=r.objects?.[obj.object_id];if(!tile)continue;const [x,y]=this.game.room.center(tile),sprite=this.game.art.roles.objective?.[obj.kind]||'orb_cyan',bb=this.spriteBBox(sprite,x,y+10,true,1);bb.y0=Math.min(bb.y0,y-46);bb.x0=Math.min(bb.x0,x-28);bb.x1=Math.max(bb.x1,x+28);out.push({type:'objective',objectOnly:true,id:obj.object_id,obj,tile:[...tile],bbox:bb})}
      (r.moth_pickups||[]).forEach((m,i)=>{const [tx,ty]=m.tile||[0,0],[x,y]=this.game.room.center([tx,ty]),sprite=(this.game.art.roles.moths||[])[(m.variant||0)%Math.max(1,(this.game.art.roles.moths||[]).length)];out.push({type:'moth',objectOnly:true,id:m.id||`moth:${i}`,index:i,obj:m,tile:[tx,ty],bbox:this.spriteBBox(sprite,x,y,false,.48)})});
      (r.creature_groups||[]).forEach((cg,i)=>{const live=(this.game.creatures?.units||[]).filter(u=>String(u.id||'').startsWith(String(cg.id)+'_'));const frames=this.game.art.roles.creatures?.[cg.kind]||{},sprite=frames.idle;const points=live.length?live.map(u=>[u.x,u.y]):[this.game.room.center(cg.spawn||[0,0])];for(let j=0;j<points.length;j++){const [x,y]=points[j];out.push({type:'wildlife',objectOnly:true,id:String(cg.id||`wildlife:${i}`),index:i,obj:cg,tile:[...(cg.spawn||[0,0])],bbox:this.spriteBBox(sprite,x,y,false,(cg.kind==='pixie'||cg.kind==='mushroom_pixie')?1.62:1.755)})}});
      (r.mini_robot_groups||[]).forEach((mg,i)=>{const [x,y]=this.game.room.center(mg.spawn||[0,0]),sprite=this.game.art.roles.mini_robots?.[mg.variant||'teal']?.idle;out.push({type:'mini',objectOnly:true,id:String(mg.id||`mini:${i}`),index:i,obj:mg,tile:[...(mg.spawn||[0,0])],bbox:this.spriteBBox(sprite,x,y,false,1.52)})});
      out.push(...this.patternItems(r));return out}
    patternItems(r){const out=[],p=this.game.room.spec.pattern||this.game.room.spec.key,cx=W/2,cy=PLAY_H*.54,hidden=new Set((r.pattern_exclusions||[]).map(String)),add=(id,sprite,x,y,scale=1,label=id)=>{if(hidden.has(id)||!this.game.art.regions[sprite])return;out.push({type:'pattern',objectOnly:true,id,obj:{label,sprite,x,y,scale},bbox:this.spriteBBox(sprite,x,y,false,scale)})};if(p==='nest')add('nest:swirl','swirl_large',cx,cy+25,1.3,'Moon / star swirl');if(p==='lane')[[0,145,'candelabra_small'],[1,320,'candelabra_wide'],[2,495,'candelabra_small']].forEach(([i,x,s])=>add(`lane:lamp:${i}`,s,x,125,1,`Lane lamp ${i+1}`));if(p==='home')add('home:orb',(this.game.art.roles.objective?.beacon==='orb_green')?'orb_magenta':'orb_green',cx+82,cy+29,1,'Home orb');if(p==='orchard')for(let i=0;i<4;i++)add(`orchard:lamp:${i}`,'candelabra_small',150+i*115,103,1,`Orchard lamp ${i+1}`);if(p==='battery'){const orbs=['orb_magenta','orb_green','orb_orange','orb_cyan','orb_purple'];for(let i=0;i<orbs.length;i++){const a=i/orbs.length*TAU-.5,rr=82;add(`battery:orb:${i}`,orbs[i],cx+Math.cos(a)*rr,cy+Math.sin(a)*rr*.52,1,`Battery orb ${i+1}`)}}if(p==='dawn'){add('dawn:orb','orb_orange',cx,150,1.25,'Dawn orb');if(this.game.state.roomComplete(this.game.room.spec))add('dawn:swirl','swirl_large',cx,cy+20,1.45,'Dawn star swirl')}if(p==='ferns'){const names=this.game.art.roles.decor_plants||[];for(let i=0;i<10;i++){const a=i/10*TAU,rr=75,n=names[i%Math.max(1,names.length)];if(n)add(`ferns:${i}`,n,cx+Math.cos(a)*rr,cy+Math.sin(a)*rr*.56+22,1,`Fern ring ${i+1}`)}}if(p==='garden'){const names=['bush_yellow','bush_blue','bush_pair','flower_pink','flower_blue','flower_bush'];for(let i=0;i<24;i++){const seed=hash32(i,this.game.room.index,440),x=42+(seed%555),y=72+((seed>>>8)%175),n=names[i%names.length];if(this.game.art.regions[n])add(`garden:${i}`,n,x,y+18,1,`Garden decor ${i+1}`)}}return out}
    spriteBBox(sprite,x,y,bottom=true,scale=1,rot=0){if(!sprite||!this.game.art.regions[sprite])return{x0:x-8,y0:y-16,x1:x+8,y1:y};const [w,h]=this.game.art.worldSize(sprite,scale),top=bottom?-h:-h/2,co=Math.cos(rot),si=Math.sin(rot),pts=[[-w/2,top],[w/2,top],[-w/2,top+h],[w/2,top+h]].map(([px,py])=>[x+co*px-si*py,y+si*px+co*py]);return{x0:Math.min(...pts.map(p=>p[0])),y0:Math.min(...pts.map(p=>p[1])),x1:Math.max(...pts.map(p=>p[0])),y1:Math.max(...pts.map(p=>p[1]))}}
    hitAt(p,includeTiles=true,objectOnly=false){const items=this.collectItems().filter(it=>(!objectOnly||it.objectOnly)&& (includeTiles||!['path','water'].includes(it.type))&&p.x>=it.bbox.x0&&p.x<=it.bbox.x1&&p.y>=it.bbox.y0&&p.y<=it.bbox.y1);return items.length?items[items.length-1]:null}
    removeRef(ref){const r=this.rawRoom();if(ref.type==='blocker'||ref.type==='tree'||ref.type==='water'||ref.type==='path'){const [tx,ty]=ref.tile,k=key(tx,ty);for(const n of ['walls','water','path_cells'])r[n]=(r[n]||[]).filter(q=>key(q[0],q[1])!==k);if(r.blocker_styles)delete r.blocker_styles[k];r.large_trees=(r.large_trees||[]).filter(t=>key(t.tile?.[0],t.tile?.[1])!==k);return}if(ref.type==='decor'){const a=r.editor_decor||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1);else r.editor_decor=a.filter((d,j)=>(d.editor_id||`decor:${j}`)!==ref.id)}else if(ref.type==='grass'){const a=r.grass_clumps||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='lamp'){const a=r.decor_lamps||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='robot'){const a=r.decor_robots||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='moth'){const a=r.moth_pickups||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='wildlife'){const a=r.creature_groups||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='mini'){const a=r.mini_robot_groups||[],i=ref.obj?a.indexOf(ref.obj):-1;if(i>=0)a.splice(i,1)}else if(ref.type==='pattern'){r.pattern_exclusions=r.pattern_exclusions||[];if(!r.pattern_exclusions.includes(ref.id))r.pattern_exclusions.push(ref.id)}else if(ref.type==='objective'){r.object_fx_hidden=r.object_fx_hidden||[];if(!r.object_fx_hidden.includes(ref.id))r.object_fx_hidden.push(ref.id)}}
    deleteSelection(){if(!this.selection.length)return;this.beginTransaction('delete selection');for(const s of [...this.selection].reverse())this.removeRef(s);this.selection=[];this.rebuildRoom();this.commitTransaction()}
    captureSelectionState(){const r=this.rawRoom(),states=[];for(const ref of this.selection){if(ref.type==='decor'){const d=(r.editor_decor||[]).find((d,i)=>(d.editor_id||`decor:${i}`)===ref.id);if(d)states.push({ref,kind:'pixel',x:d.x,y:d.y})}else if(ref.type==='grass'){const g=ref.obj||(r.grass_clumps||[])[ref.index];if(g)states.push({ref,kind:'pixel',x:g.x,y:g.y})}else if(['lamp','robot','blocker','tree','water','path','objective','moth','wildlife','mini'].includes(ref.type)){states.push({ref,kind:'tile',tx:ref.tile[0],ty:ref.tile[1]})}else if(ref.type==='pattern'){states.push({ref,kind:'pixel',x:(ref.bbox.x0+ref.bbox.x1)/2,y:(ref.bbox.y0+ref.bbox.y1)/2})}}return states}
    previewMove(){this.renderOverlay()}
    applyMove(p){if(!this.moveOriginal||!this.dragStart)return;const dx=p.x-this.dragStart.x,dy=p.y-this.dragStart.y,tdx=Math.round(dx/TILE),tdy=Math.round(dy/TILE),r=this.rawRoom();if(this.selection.some(s=>s.type==='pattern')){this.game.toast('Procedural ambient objects can be removed or replaced, but not moved directly.',1.7);return}const copies=this.copySelectionData(this.selection);for(const ref of [...this.selection].reverse()){if(ref.type==='objective')continue;this.removeRef(ref)}for(const c of copies){if(c.type==='objective'){r.objects[c.data.object_id]=[clamp(c.tx+tdx,0,GRID_W-1),clamp(c.ty+tdy,0,GRID_H-1)];r.object_fx_hidden=(r.object_fx_hidden||[]).filter(id=>id!==c.data.object_id)}else this.pasteDataItem(c,c.kind==='pixel'?dx:tdx,c.kind==='pixel'?dy:tdy,true)}this.selection=[];this.rebuildRoom()}
    copySelectionData(refs){const r=this.rawRoom(),out=[];for(const ref of refs){if(ref.type==='decor'){const d=(r.editor_decor||[]).find((d,i)=>(d.editor_id||`decor:${i}`)===ref.id);if(d)out.push({type:'decor',kind:'pixel',data:clone(d),x:d.x,y:d.y})}else if(ref.type==='grass'){const g=ref.obj||(r.grass_clumps||[])[ref.index];if(g)out.push({type:'grass',kind:'pixel',data:clone(g),x:g.x,y:g.y})}else if(ref.type==='lamp'){const d=ref.obj||(r.decor_lamps||[])[ref.index];if(d)out.push({type:'lamp',kind:'tile',data:clone(d),tx:d.tile[0],ty:d.tile[1]})}else if(ref.type==='robot'){const d=ref.obj||(r.decor_robots||[])[ref.index];if(d)out.push({type:'robot',kind:'tile',data:clone(d),tx:d.tile[0],ty:d.tile[1]})}else if(ref.type==='objective'){const tile=r.objects?.[ref.id];if(tile)out.push({type:'objective',kind:'tile',data:{object_id:ref.id},tx:tile[0],ty:tile[1]})}else if(ref.type==='moth'){const d=ref.obj||(r.moth_pickups||[])[ref.index];if(d)out.push({type:'moth',kind:'tile',data:clone(d),tx:d.tile[0],ty:d.tile[1]})}else if(ref.type==='wildlife'){const d=ref.obj||(r.creature_groups||[])[ref.index];if(d)out.push({type:'wildlife',kind:'tile',data:clone(d),tx:d.spawn[0],ty:d.spawn[1]})}else if(ref.type==='mini'){const d=ref.obj||(r.mini_robot_groups||[])[ref.index];if(d)out.push({type:'mini',kind:'tile',data:clone(d),tx:d.spawn[0],ty:d.spawn[1]})}else if(ref.type==='tree'){const style=clone(r.blocker_styles?.[ref.id]||{}),tree=(r.large_trees||[]).find(t=>key(t.tile?.[0],t.tile?.[1])===ref.id);out.push({type:'tree',kind:'tile',data:{style,tree:clone(tree)},tx:ref.tile[0],ty:ref.tile[1]})}else if(ref.type==='blocker'){out.push({type:'blocker',kind:'tile',data:{style:clone(r.blocker_styles?.[ref.id]||{})},tx:ref.tile[0],ty:ref.tile[1]})}else if(ref.type==='water'||ref.type==='path')out.push({type:ref.type,kind:'tile',data:{},tx:ref.tile[0],ty:ref.tile[1]})}return out}
    copySelection(){if(!this.selection.length)return;const data=this.copySelectionData(this.selection);if(!data.length)return;const xs=data.map(d=>d.kind==='pixel'?d.x:d.tx*TILE+TILE/2),ys=data.map(d=>d.kind==='pixel'?d.y:d.ty*TILE+TILE/2);this.clipboard={items:data,anchor:{x:Math.min(...xs),y:Math.min(...ys)}};this.game.toast(`Copied ${data.length} editor item${data.length===1?'':'s'}`,1.2);this.updateStatus()}
    pasteClipboard(){if(!this.clipboard?.items?.length)return;this.beginTransaction('paste');const ox=this.hover.x-this.clipboard.anchor.x,oy=this.hover.y-this.clipboard.anchor.y,tdx=Math.round(ox/TILE),tdy=Math.round(oy/TILE);this.selection=[];for(const c of this.clipboard.items)this.pasteDataItem(c,c.kind==='pixel'?ox:tdx,c.kind==='pixel'?oy:tdy,false);this.rebuildRoom();this.commitTransaction();this.game.toast(`Pasted ${this.clipboard.items.length} item${this.clipboard.items.length===1?'':'s'}`,1.1)}
    pasteDataItem(c,dx,dy,moving=false){const r=this.rawRoom();if(c.kind==='pixel'){const d=clone(c.data);d.x=clamp(Math.round((c.x+dx)*100)/100,0,W);d.y=clamp(Math.round((c.y+dy)*100)/100,0,PLAY_H);if(c.type==='decor'){d.editor_id=`decor_${this.nextDecorId++}`;r.editor_decor=r.editor_decor||[];r.editor_decor.push(d)}else{d.seed=moving?d.seed:((Number(d.seed)||Date.now())+this.nextDecorId*7919)>>>0;r.grass_clumps=r.grass_clumps||[];r.grass_clumps.push(d)}return}const tx=clamp(c.tx+dx,0,GRID_W-1),ty=clamp(c.ty+dy,0,GRID_H-1);if(c.type==='path'||c.type==='water')this.placeTile({kind:c.type},tx,ty);else if(c.type==='blocker'){this.placeTile({kind:'blocker',sprite:c.data.style?.sprite},tx,ty);r.blocker_styles[key(tx,ty)]={...c.data.style}}else if(c.type==='tree'){const sprite=c.data.tree?.sprite||c.data.style?.sprite;this.placeTile({kind:'tree',sprite},tx,ty);r.blocker_styles[key(tx,ty)]={...c.data.style,sprite:c.data.style?.sprite||sprite};const tree=(r.large_trees||[]).find(t=>t.tile?.[0]===tx&&t.tile?.[1]===ty);if(tree)tree.sprite=c.data.tree?.sprite||sprite}else if(c.type==='lamp'){const d=clone(c.data);d.tile=[tx,ty];this.replaceByTile(r.decor_lamps=r.decor_lamps||[],tx,ty,d)}else if(c.type==='robot'){const d=clone(c.data);d.tile=[tx,ty];delete d.id;this.replaceByTile(r.decor_robots=r.decor_robots||[],tx,ty,d)}else if(c.type==='moth'){const d=clone(c.data);d.tile=[tx,ty];if(!moving)d.id=this.uniqueId('editor_moth',r.moth_pickups||[]);(r.moth_pickups=r.moth_pickups||[]).push(d)}else if(c.type==='wildlife'){const d=clone(c.data);d.spawn=[tx,ty];if(!moving)d.id=this.uniqueId(`editor_${d.kind||'wildlife'}`,r.creature_groups||[]);(r.creature_groups=r.creature_groups||[]).push(d)}else if(c.type==='mini'){const d=clone(c.data);d.spawn=[tx,ty];if(!moving)d.id=this.uniqueId(`editor_mini_${d.variant||'teal'}`,r.mini_robot_groups||[]);(r.mini_robot_groups=r.mini_robot_groups||[]).push(d)}}
    updateStatus(){if(!this.status)return;this.status.textContent=`${this.roomKey()} · ${this.tool.toUpperCase()} · ${this.choice?.label||''} · selected ${this.selection.length} · undo ${this.undo.length}${this.clipboard?` · clipboard ${this.clipboard.items.length}`:''}`}
    rebuildRoom(){const idx=this.game.state.room,spec=this.game.storyData.rooms[idx],old=this.game.room;this.game.rooms[idx]=new Room(idx,spec,this.game.maps);this.game.room=this.game.rooms[idx];this.game.room.bridgeProgress=old?.bridgeProgress||0;this.game.room.bridgeBuilt=old?.bridgeBuilt||false;if(!this.game.room.walkablePixel(this.game.x,this.game.y,PLAYER_COLLISION_R)){const t=this.game.room.nearestClearWalkable(this.game.room.tile(this.game.x,this.game.y),PLAYER_COLLISION_R);[this.game.x,this.game.y]=this.game.room.center(t)}this.game.bgKey='';this.game.ensureBackground(true);this.game.creatures?.init(this.game.room);this.game.miniGuides?.init(this.game.room,this.game.state);this.renderOverlay();this.updateStatus()}
    ghostGeometry(e){const centred=['moth','wildlife','mini'].includes(e.kind);let scale=e.scale??1;if(e.kind==='robot')scale=.84;else if(e.kind==='lamp')scale=.66;else if(e.kind==='moth')scale=.36;else if(e.kind==='mini')scale=1.52;else if(e.kind==='wildlife')scale=['pixie','mushroom_pixie'].includes(e.wildlifeKind)?1.62:1.755;if(!centred)scale=this.game.painter.spriteScale(e.sprite,scale);return{scale,anchor:centred?'center':'bottom',alpha:.56*(e.alpha??1)}}
    drawSpriteGhost(ctx,e,x,y,alpha=.56){if(!e?.sprite||!this.game.art.regions[e.sprite])return;const geometry=this.ghostGeometry(e);this.game.art.draw(ctx,e.sprite,x,y,null,null,{...geometry,alpha:alpha*(e.alpha??1),flip:!!e.flip,rot:Number(e.rot)||0})}
    drawLampGhost(ctx,e,x,y){this.drawSpriteGhost(ctx,{kind:'decor',sprite:'orb_pillar',scale:.92},x,y+11);this.drawSpriteGhost(ctx,e,x,y-18)}
    renderOverlay(){if(!this.overlay)return;const c=this.ctx;c.clearRect(0,0,W,H);if(!this.active)return;if(this.showGrid){c.save();c.strokeStyle='#6ff4dd28';c.lineWidth=1;for(let x=0;x<=W;x+=TILE){c.beginPath();c.moveTo(x+.5,0);c.lineTo(x+.5,PLAY_H);c.stroke()}for(let y=0;y<=PLAY_H;y+=TILE){c.beginPath();c.moveTo(0,y+.5);c.lineTo(W,y+.5);c.stroke()}c.restore()}
      if(this.tool==='object'){c.save();c.font='7px "Cascadia Mono",Consolas,monospace';c.textBaseline='bottom';for(const it of this.collectItems().filter(x=>x.objectOnly)){const selected=this.selection.some(s=>this.sameRef(s,it));c.strokeStyle=selected?'#ffe970cc':'#75f6ff66';c.fillStyle=selected?'#ffe970':'#a8ffffbb';c.lineWidth=selected?1.5:1;c.setLineDash([3,3]);const w=it.bbox.x1-it.bbox.x0,h=it.bbox.y1-it.bbox.y0;c.strokeRect(it.bbox.x0+.5,it.bbox.y0+.5,w-1,h-1);const label=it.type==='objective'?`OBJ ${it.id}`:it.type==='wildlife'?`${it.obj?.kind||'wildlife'} ×${it.obj?.count||1}`:it.type==='moth'?`MOTH ${it.obj?.id||''}`:it.type==='mini'?`MINI ${it.obj?.variant||''}`:it.type==='pattern'?(it.obj?.label||it.id):it.type;c.fillText(label,it.bbox.x0+2,Math.max(9,it.bbox.y0-1))}c.restore()}
      for(const s of this.selection){c.save();c.strokeStyle='#ffe970';c.fillStyle='#ffe97018';c.lineWidth=1.8;c.setLineDash([5,3]);c.fillRect(s.bbox.x0,s.bbox.y0,s.bbox.x1-s.bbox.x0,s.bbox.y1-s.bbox.y0);c.strokeRect(s.bbox.x0+.5,s.bbox.y0+.5,s.bbox.x1-s.bbox.x0-1,s.bbox.y1-s.bbox.y0-1);c.restore()}
      if(this.dragMode==='selectBox'&&this.dragStart&&this.dragNow){const r=rectFrom(this.dragStart,this.dragNow);c.save();c.strokeStyle='#95ffff';c.fillStyle='#5be7ff18';c.setLineDash([4,3]);c.strokeRect(r.x0,r.y0,r.x1-r.x0,r.y1-r.y0);c.fillRect(r.x0,r.y0,r.x1-r.x0,r.y1-r.y0);c.restore()}
      if(this.dragMode==='move'&&this.dragStart&&this.dragNow){const dx=this.dragNow.x-this.dragStart.x,dy=this.dragNow.y-this.dragStart.y;c.save();c.strokeStyle='#ff9ce2';c.setLineDash([3,3]);for(const s of this.selection)c.strokeRect(s.bbox.x0+dx,s.bbox.y0+dy,s.bbox.x1-s.bbox.x0,s.bbox.y1-s.bbox.y0);c.restore()}
      if(!this.pointerDown&&this.tool==='brush'&&this.choice){const [tx,ty]=this.tileAt(this.hover),x=tx*TILE+TILE/2,y=ty*TILE+TILE;if(['path','water','solid','clear','blocker','tree'].includes(this.choice.kind)){c.save();c.fillStyle=this.choice.kind==='water'?'#42c7ff38':this.choice.kind==='path'?'#ffd17b35':'#bbff9c25';c.strokeStyle='#eaffffaa';c.fillRect(tx*TILE,ty*TILE,TILE,TILE);c.strokeRect(tx*TILE+.5,ty*TILE+.5,TILE-1,TILE-1);c.restore();if(this.choice.sprite)this.drawSpriteGhost(c,this.choice,x,y+2)}else if(this.choice.kind==='grass'){c.save();c.strokeStyle='#75ffb8bb';c.fillStyle='#58de8e24';c.beginPath();c.ellipse(this.hover.x,this.hover.y,this.choice.radius,this.choice.radius*.7,0,0,Math.PI*2);c.fill();c.stroke();c.restore()}else if(this.choice.kind==='decor')this.drawSpriteGhost(c,this.choice,this.hover.x,this.hover.y);else if(this.choice.kind==='lamp')this.drawLampGhost(c,this.choice,tx*TILE+TILE/2,ty*TILE+TILE/2);else if(this.choice.kind==='robot')this.drawSpriteGhost(c,this.choice,tx*TILE+TILE/2,ty*TILE+TILE/2+10);else if(['moth','wildlife','mini'].includes(this.choice.kind))this.drawSpriteGhost(c,this.choice,tx*TILE+TILE/2,ty*TILE+TILE/2);else if(this.choice.kind==='ambient')this.drawSpriteGhost(c,this.choice,this.hover.x,this.hover.y)}
    }
    async saveProject(){if(location.hostname.endsWith('.github.io')){this.downloadMaps();return}try{const res=await fetch('/__editor/save_maps',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(this.game.maps,null,2)+'\n'});if(!res.ok)throw new Error((await res.text())||`HTTP ${res.status}`);const data=await res.json();this.game.toast(`Saved relay_moth_maps.json · backup ${data.backup||'created'}`,2)}catch(e){this.game.toast('Project save unavailable · use Download JSON · '+e.message,3)}}
    downloadMaps(){download('relay_moth_maps.json',JSON.stringify(this.game.maps,null,2)+'\n');this.game.toast('Map JSON downloaded',1.2)}
  }

  root.setupWysiwygEditor=function(game){if(root.rmfEditor)return root.rmfEditor;root.rmfEditor=new WysiwygEditor(game);return root.rmfEditor};
  root.toggleWysiwygEditor=function(){root.rmfEditor?.toggle()};
})(typeof globalThis!=='undefined'?globalThis:window);
